FLAGS := -ggdb -std=c++11
all:
	mkdir -p bin
	g++ $(FLAGS) -o bin/cbuffer                   cbuffer.cpp
	g++ $(FLAGS) -o bin/2numbers                  2numbers.cpp
	g++ $(FLAGS) -o bin/numReverse                numReverse.cpp
	g++ $(FLAGS) -o bin/atoi                      atoi.cpp
	g++ $(FLAGS) -o bin/divison                   division.cpp
	g++ $(FLAGS) -o bin/anagram                   anagram.cpp
	g++ $(FLAGS) -o bin/binadd                    binadd.cpp
	g++ $(FLAGS) -o bin/dupremove                 dupremove.cpp
	g++ $(FLAGS) -o bin/linkadd                   linkadd.cpp
	g++ $(FLAGS) -o bin/longsubpalindrome         longsubpalindrome.cpp
clean:
	rm -rf bin
	rm -rf *.out
