FLAGS := -ggdb -std=c++11
all:
	mkdir -p bin
	g++ $(FLAGS) -o bin/cbuffer     cbuffer.cpp
	g++ $(FLAGS) -o bin/2numbers    2numbers.cpp
	g++ $(FLAGS) -o bin/numReverse  numReverse.cpp
clean:
	rm -rf bin
